# Generated by Django 4.2.6 on 2023-11-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(1, 'Detalles'), (0, 'Alimentos Dulces'), (4, 'Utencilios'), (3, 'Miscelania'), (2, 'Mecatos')]),
        ),
    ]
