# Generated by Django 4.2.6 on 2023-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.TextField(blank=True, null=True)),
                ('tarjeta', models.TextField(blank=True, null=True)),
                ('expira_month', models.TextField(blank=True, null=True)),
                ('expira_year', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.TextField(blank=True, null=True)),
                ('pais', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
